export const DEFAULT_COLDSTART_MODEL = "claude-sonnet-5";

export const MODEL_REQUEST_TIMEOUT_MS = 30_000;

export const MODEL_CALL_MAX_RETRIES = 0;

export const CANDIDATE_DATA_DELIMITER = "<<<GROWTHMIND_CANDIDATE_DATA>>>";
