// Drizzle schema barrel. Every table lives in a file per subsystem and is re-exported
// here; drizzle-kit reads this file to generate migrations.
//
// auth.ts is generated by Better Auth's CLI from apps/web/lib/auth.ts (`bunx
// @better-auth/cli generate`). Regenerate it when the auth config changes rather than
// editing it by hand.
export * from "./auth";
export * from "./projects";
export * from "./write-keys";
export * from "./project-connections";
export * from "./sessions";
export * from "./events";
export * from "./session-source-poll-runs";
export * from "./finding-signatures";
export * from "./dismissals";
export * from "./signature-ancestry";
export { deliveries } from "./deliveries";
export { apiKeys } from "./api-keys";
// The analysis lane. `analysis-runs` first: `findings` and `analysis-model-calls` both
// reference it.
export * from "./analysis-runs";
export * from "./findings";
export * from "./analysis-model-calls";
// The first-run surface (O-008). `slack_connections` is org-scoped and depends
// only on `auth`; the two `first_run_*` tables are two grains and deliberately
// two tables (AD-8).
export * from "./slack-connections";
export * from "./first-run-state";
export * from "./first-run-dismissals";
