// Drizzle schema barrel. Every table lives in a file per subsystem and is
// re-exported here; drizzle-kit reads this file to generate migrations.
//
// auth.ts is generated by Better Auth's CLI from apps/web/lib/auth.ts
// (`bunx @better-auth/cli generate`) — regenerate it when the auth config
// changes rather than editing it by hand.
export * from "./auth";
