// THE STATE MAC'S DOMAIN SEPARATION — M-1.
//
// ###########################################################################
// # `BETTER_AUTH_SECRET` SIGNS TWO DIFFERENT THINGS.
// #
// # Better Auth signs its session cookies with it, and `signOAuthState` signs
// # the OAuth state MAC with it. Two mechanisms under one key with no
// # separation means a signature minted by either is a signature the other
// # accepts — so the day any Better Auth surface HMACs a caller-influenced
// # value under this key, that surface is a signing oracle and a forged state
// # follows immediately: sign a payload of the attacker's choosing, present it
// # as both the cookie and the `state` parameter (they are the same string),
// # and the callback seals the attacker's Slack workspace into whatever
// # organisation the payload names.
// #
// # No such oracle exists today, which is why this was filed MEDIUM rather
// # than HIGH. The row below is priced against a dependency upgrade adding
// # one, not against a present exploit.
// ###########################################################################
//
// ── WHY THE ROW MODELS THE ORACLE RATHER THAN ASSERTING A LITERAL ───────────
//
// Asserting that the digest equals some hard-coded base64url string would pin
// the label's exact bytes and nothing about what the label is FOR — and it
// would have to be regenerated by whoever changed the label, which is the one
// moment the assertion needs to mean something.
//
// So the row computes the signature an unlabelled HMAC under the same secret
// produces — precisely what a Better Auth signing oracle would hand an attacker
// — and asserts the verifier refuses it. Delete the label from `signPart` and
// that signature starts verifying, which is this row going red.
import { createHmac } from "node:crypto";

import { describe, expect, test } from "bun:test";

import { signOAuthState, verifyOAuthState } from "../../lib/slack/oauth";

/** THIS REPOSITORY IS PUBLIC. Not, and not resembling, a real
 *  `BETTER_AUTH_SECRET`. */
const SECRET = "first-run-oauth-fixture-secret-not-a-real-one";

const SIGNED_AT = new Date("2026-08-01T10:00:00.000Z");

const IDENTITY = { userId: "usr_founder_of_org_a", organizationId: "org_a" };

const clockAt =
  (instant: Date): (() => Date) =>
  () =>
    new Date(instant.getTime());

describe("the OAuth state MAC is domain-separated from Better Auth's own signing", () => {
  test("a signature from an unlabelled HMAC under the same secret is refused", () => {
    const signed = signOAuthState(
      { identity: IDENTITY },
      { secret: SECRET, now: clockAt(SIGNED_AT), nonce: () => "nonce-one" },
    );

    const [encodedPayload] = signed.stateParameter.split(".");

    // What a signing oracle keyed by `BETTER_AUTH_SECRET` — any Better Auth
    // surface that HMACs a caller-influenced value — would return for this
    // payload. Genuine bytes under the genuine key; the ONLY thing missing is
    // the label this file exists for.
    const oracleSignature = createHmac("sha256", SECRET).update(encodedPayload).digest("base64url");
    const forged = `${encodedPayload}.${oracleSignature}`;

    const result = verifyOAuthState(
      { cookieValue: forged, stateParameter: forged, expected: IDENTITY },
      { secret: SECRET, now: clockAt(new Date(SIGNED_AT.getTime() + 30_000)) },
    );

    expect(result).toEqual({ ok: false, code: "state_signature_invalid" });
  });

  test("a state this file signed still verifies — the label is on both sides", () => {
    // The other half. A label applied in the signer and forgotten in the
    // verifier refuses every legitimate round trip, and the symptom would be
    // "Add to Slack" never working for anybody rather than a security hole.
    // `signPart` is one producer for both directions, and this row is what says
    // so out loud.
    const signed = signOAuthState(
      { identity: IDENTITY },
      { secret: SECRET, now: clockAt(SIGNED_AT), nonce: () => "nonce-one" },
    );

    const result = verifyOAuthState(
      {
        cookieValue: signed.cookieValue,
        stateParameter: signed.stateParameter,
        expected: IDENTITY,
      },
      { secret: SECRET, now: clockAt(new Date(SIGNED_AT.getTime() + 30_000)) },
    );

    expect(result).toEqual({ ok: true });
  });
});
